app:
  package_name: pdf.reader.pdf.viewer.all.document.reader.office.viewer
  main_activity: com.simple.pdf.reader.ui.main.SplashScreenActivity
apks:
  dir: apks
device:
  exclude: []
  launch_timeout: 15
  ui_timeout: 10
appium:
  host: 127.0.0.1
  port: 4723
test:
  screenshot_on_failure: true
  record_video: true
  video_save_mode: always
  video_quality: low
  step_delay: 1
  retry_count: 1
test_pdfs:
  simple: tests/resources/sample_simple.pdf
  large: tests/resources/sample_large.pdf
